services:
  dev:
    build:
      context: .
      dockerfile: Containerfile.dev
    security_opt:
      - label=disable
    env_file:
      - .dev.env

  database:
    image: docker.io/postgres:18.2
    security_opt:
      - label=disable
    environment:
      POSTGRES_USER: techtonic
      POSTGRES_PASSWORD: H34AGlTYqH
      POSTGRES_DB: techtonic
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    

  redis:
    image: docker.io/redis:8.2.0-alpine
    restart: always
    security_opt:
      - label=disable
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass techtonicz
    volumes:
      - redis:/data
  rustfs:
    image: docker.io/rustfs/rustfs:alpha
    security_opt:
      - label=disable
    ports:
      - "9000:9000"
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
    environment:
      RUSTFS_ROOT_USER: rustfsadmin
      RUSTFS_ROOT_PASSWORD: rustfsadmin
    
volumes:
  pg_data:
  redis:
  rustfs_data:
  rustfs_logs:
