FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN apt update -y
RUN apt install -y protobuf-compiler wget

# Install grpcurl
RUN wget https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_amd64.deb -O /tmp/grpcurl.deb && \
    dpkg -i /tmp/grpcurl.deb && \
    rm /tmp/grpcurl.deb