FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN apt update -y
RUN apt install -y protobuf-compiler wget

# Install grpcurl
RUN wget https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_amd64.deb -O /tmp/grpcurl.deb && \
    dpkg -i /tmp/grpcurl.deb && \
    rm /tmp/grpcurl.deb

RUN gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://://ubuntu.com --recv-keys C5AD17C747E3415A36772591379F51240E103E01

# 2. Add the repository
RUN echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" |  tee /etc/apt/sources.list.d/k6.list

# 3. Update and install
RUN apt-get update
RUN apt-get install k6