// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechtonicCmsApi.Schema.TechtonicCms;

#nullable disable

namespace TechtonicCmsApi.Migrations
{
    [DbContext(typeof(TechtonicCmsDbContext))]
    [Migration("20260330211851_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attribute_path", new[] { "subject_id", "subject_role", "subject_status", "subject_created_at", "resource_collection_id", "resource_collection_slug", "resource_collection_created_by", "resource_collection_is_localized", "resource_entry_id", "resource_entry_status", "resource_entry_created_by", "resource_entry_collection_id", "resource_entry_locale", "resource_entry_published_at", "resource_field_id", "resource_field_name", "resource_field_data_type", "resource_field_sensitivity_level", "resource_field_is_pii", "resource_field_is_public", "resource_field_collection_id", "resource_asset_id", "resource_asset_uploaded_by", "resource_asset_mime_type", "resource_asset_file_size", "environment_current_time", "environment_ip_address", "environment_user_agent", "action_type" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "base_resource", new[] { "users", "collections", "entries", "assets", "fields" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "data_type", new[] { "text", "typst_text", "boolean", "number", "date_time", "relation", "text_list", "number_list", "asset", "rich_text", "json" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "entry_status", new[] { "draft", "published", "archived", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "locale", new[] { "en", "es", "fr", "de", "it", "pt", "ja", "ko", "zh", "ar", "ru" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "logical_operator", new[] { "and", "or" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "operator_type", new[] { "eq", "ne", "in", "not_in", "gt", "gte", "lt", "lte", "contains", "starts_with", "ends_with", "is_null", "is_not_null", "regex" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permission_action", new[] { "create", "read", "update", "delete", "publish", "unpublish", "schedule", "archive", "restore", "draft", "ban", "unban", "activate", "deactivate", "upload", "download", "transform", "configure_fields", "manage_schema" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permission_effect", new[] { "allow", "deny" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "active", "inactive", "banned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "value_type", new[] { "string", "number", "boolean", "uuid", "datetime", "array" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<Guid[]>("EvaluatedPolicyIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("EvaluationTimeMs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.PrimitiveCollection<Guid[]>("MatchingPolicyIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("RequestContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestedAction")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationTimeMs");

                    b.HasIndex("FieldId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Decision", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.HasIndex("ResourceType", "ResourceId", "Timestamp");

                    b.ToTable("abac_audit");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacEvaluationCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ContextChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<int>("EvaluationTimeMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("MatchingPolicyIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("PolicyVersions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContextChecksum");

                    b.HasIndex("Decision");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId", "FieldId", "ActionType");

                    b.HasIndex("UserId", "ResourceType", "ResourceId", "ActionType");

                    b.ToTable("abac_evaluation_cache");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Effect")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<int>("RuleConnector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Priority");

                    b.HasIndex("ResourceType", "ActionType");

                    b.ToTable("abac_policies");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttributePath")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExpectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Operator")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributePath");

                    b.HasIndex("PolicyId", "IsActive");

                    b.HasIndex("PolicyId", "Order");

                    b.ToTable("abac_policy_rules");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultLocale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsLocalized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.PrimitiveCollection<string[]>("SupportedLocales")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new[] { "en" });

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("collections");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultLocale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Locale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("entries");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryAsset", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("EntryId", "FieldId", "AssetId");

                    b.HasIndex("AssetId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_assets");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryBoolean", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool?>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("EntryId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_booleans");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryDateTime", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("Value")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntryId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_datetimes");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryJsonData", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EntryId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_json_data");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryNumber", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Value")
                        .HasColumnType("integer");

                    b.HasKey("EntryId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_numbers");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryRelation", b =>
                {
                    b.Property<Guid>("FromEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FromEntryId", "FieldId", "ToEntryId");

                    b.HasIndex("FieldId");

                    b.HasIndex("ToEntryId");

                    b.ToTable("entry_relations");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryRichText", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("markdown");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rendered")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("EntryId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_rich_texts");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryText", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("EntryId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_texts");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryTypstText", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rendered")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("EntryId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("entry_typst_texts");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsEncrypted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SensitivityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PUBLIC");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsPii");

                    b.HasIndex("SensitivityLevel");

                    b.HasIndex("CollectionId", "Name")
                        .IsUnique();

                    b.ToTable("fields");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.ResourceOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("CREATOR");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OwnerId", "ResourceType");

                    b.HasIndex("ResourceType", "ResourceId", "OwnerId");

                    b.ToTable("resource_ownerships");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("LastEditTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.RolePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RoleId", "PolicyId")
                        .IsUnique();

                    b.ToTable("role_policies");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastEditTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastLoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.UserPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId", "PolicyId")
                        .IsUnique();

                    b.ToTable("user_policies");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacAudit", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("AuditLogs")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacEvaluationCache", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EvaluationCaches")
                        .HasForeignKey("FieldId");

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "User")
                        .WithMany("EvaluationCaches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicy", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "CreatedByUser")
                        .WithMany("CreatedPolicies")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicyRule", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicy", "Policy")
                        .WithMany("Rules")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Asset", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "UploadedByUser")
                        .WithMany("UploadedAssets")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Collection", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "CreatedByUser")
                        .WithMany("CreatedCollections")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Collection", "Collection")
                        .WithMany("Entries")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "CreatedByUser")
                        .WithMany("CreatedEntries")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryAsset", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Asset", "Asset")
                        .WithMany("EntryAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("Assets")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryAssets")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryBoolean", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("Booleans")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryBooleans")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryDateTime", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("DateTimes")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryDateTimes")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryJsonData", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("JsonData")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryJsonData")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryNumber", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("Numbers")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryNumbers")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryRelation", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryRelations")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "FromEntry")
                        .WithMany("FromRelations")
                        .HasForeignKey("FromEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "ToEntry")
                        .WithMany("ToRelations")
                        .HasForeignKey("ToEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("FromEntry");

                    b.Navigation("ToEntry");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryRichText", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("RichTexts")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryRichTexts")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryText", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("Texts")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryTexts")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.EntryTypstText", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", "Entry")
                        .WithMany("TypstTexts")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", "Field")
                        .WithMany("EntryTypstTexts")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Collection", "Collection")
                        .WithMany("Fields")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "CreatedByUser")
                        .WithMany("CreatedFields")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.ResourceOwnership", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "AssignedByUser")
                        .WithMany("ResourcesAssignedBy")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "Owner")
                        .WithMany("OwnedResources")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.RolePolicy", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "AssignedByUser")
                        .WithMany("RolePoliciesAssignedBy")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicy", "Policy")
                        .WithMany("RolePolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Role", "Role")
                        .WithMany("RolePolicies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Policy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.UserPolicy", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "AssignedByUser")
                        .WithMany("PoliciesAssignedBy")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicy", "Policy")
                        .WithMany("UserPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "User")
                        .WithMany("AssignedPolicies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.UserRole", b =>
                {
                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.AbacPolicy", b =>
                {
                    b.Navigation("RolePolicies");

                    b.Navigation("Rules");

                    b.Navigation("UserPolicies");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Asset", b =>
                {
                    b.Navigation("EntryAssets");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Collection", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Entry", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Booleans");

                    b.Navigation("DateTimes");

                    b.Navigation("FromRelations");

                    b.Navigation("JsonData");

                    b.Navigation("Numbers");

                    b.Navigation("RichTexts");

                    b.Navigation("Texts");

                    b.Navigation("ToRelations");

                    b.Navigation("TypstTexts");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Field", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("EntryAssets");

                    b.Navigation("EntryBooleans");

                    b.Navigation("EntryDateTimes");

                    b.Navigation("EntryJsonData");

                    b.Navigation("EntryNumbers");

                    b.Navigation("EntryRelations");

                    b.Navigation("EntryRichTexts");

                    b.Navigation("EntryTexts");

                    b.Navigation("EntryTypstTexts");

                    b.Navigation("EvaluationCaches");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.Role", b =>
                {
                    b.Navigation("RolePolicies");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TechtonicCmsApi.Schema.TechtonicCms.Entities.User", b =>
                {
                    b.Navigation("AssignedPolicies");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedCollections");

                    b.Navigation("CreatedEntries");

                    b.Navigation("CreatedFields");

                    b.Navigation("CreatedPolicies");

                    b.Navigation("EvaluationCaches");

                    b.Navigation("OwnedResources");

                    b.Navigation("PoliciesAssignedBy");

                    b.Navigation("ResourcesAssignedBy");

                    b.Navigation("RolePoliciesAssignedBy");

                    b.Navigation("UploadedAssets");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
